### ISSUE TITLE
Are all techniques mentioned in paper ready in current LMCache repo?

### ISSUE THREAD

**Issue by Wesley-Jzy** [LMCache/LMCache#284]
I've read CacheGen and CacheBlend and really appreciate them. I wonder whether they are ready in current release version.

**Comment by ApostaC** [comment]
Yes. The following entries in the configuration file is related to CacheGen and CacheBlend:

```yaml
# The remote serde for the backend
# Can be "cachegen"
remote_serde: Optional[str]

# Whether to enable KV cache blending
# Set to False by default
enable_blending: bool

# The recompute ratio if KV cache blending is enabled
# Set to 0.5 by default
blend_recompute_ratio: float

# The minimum number of tokens for blending
# Set to 256 by default
blend_min_tokens: int
```

For more details, you can take a look at https://docs.lmcache.ai/configuration/config.html

The code can also be found in this repo. Please let me know if you want to learn more details.
