### ISSUE TITLE
[v0.1.0] (Bug) LMCache local agent uses unexpected amount of GPU memory and has memory leak

### ISSUE THREAD

**Issue by ApostaC** [LMCache/LMCache#63]
How to reproduce:

1. Use yaml file:
```yaml
chunk_size: 256
local_device: "cpu"
remote_serde: "cachegen"
remote_url: null

# Whether retrieve() is pipelined or not
pipelined_backend: False
```

2. use `examples/openai_chat_completition_client.py` to send a few requests
3. monitor the memory usage
