### ISSUE TITLE
[RFC]: Adopt ecosystem for managing coding style and unit testing

### ISSUE THREAD

**Issue by hickeyma** [LMCache/LMCache#634]
### Motivation.

LMCache adheres to best practices for code quality with the following tools:

- Coding style and quality:
   - Python formatters: [yapf](https://github.com/google/yapf) & [ruff](https://docs.astral.sh/ruff/)
   - Python imports formatter: [isort](https://pycqa.github.io/isort/)
   - Python linter: [ruff](https://docs.astral.sh/ruff/)
   - Python static type checker: [mypy](https://mypy-lang.org/)
   - C++ formatter: [clang-format](https://clang.llvm.org/docs/ClangFormat.html)
   - Spell checker: [codespell](https://github.com/codespell-project/codespell)
- Unit testing: [pytest](https://docs.pytest.org/en/stable/)  

These tools are implemented as follows:
 
- A [bash script](https://github.com/LMCache/LMCache/blob/dev/format.sh) to run coding style tools locally
- `pytest` from CLI to run the unit tests
- For CI, it uses [3 separate workflow files](https://github.com/LMCache/LMCache/tree/dev/.github/workflows) to call the coding style tools (yapf, ruff & mypy) directly

Standardizing the way to call the different tools would simplify maintenance and ensure tools are called the same locally and in CI.

### Proposed Change 1: [tox](https://tox.wiki)

Adopt tox to standardize the calling of tools: https://tox.wiki

Configuration would go into `tox.ini`. An example of `mypy` is as follows:

```ini
[testenv:mypy]
description = Python type checking with mypy
basepython = {[testenv:py3]basepython}
skip_install = True
skipsdist = true
deps =
  mypy>=1.15,<1.16
  types-PyYAML
  types-requests
  types-tqdm
  types-psutil
  pytest
  pydantic<=2.9.2
commands =
  mypy {posargs}
```

The configuration of `mypy` example above is set in `pyproject.yaml` as follows:

```yaml
[tool.mypy]
mypy_path = [""]
packages = ["lmcache", "tests"]
# TODO: tighten MyPy checks by enabling these checks over time
disable_error_code = [
  "no-any-return",
  "union-attr",
  "arg-type",
  "annotation-unchecked",
  "call-arg",
  "import-untyped",
  "attr-defined",
  "return-value",
  "misc",
]
# TODO: tighten MyPy checks by enabling these checks over time
check_untyped_defs = false
disallow_incomplete_defs = false
disallow_untyped_defs = false
warn_return_any = true
# honor excludes by not following there through imports
follow_imports = "silent"
ignore_missing_imports = true
```

`mypy` can be called with the following command both locally and from CI: `tox -e mypy`

### Proposed Change 2: [pre-commit](https://pre-commit.com/)

Adopt [pre-commit](https://pre-commit.com/)  for the management of code quality checking like linting, formatting spell checking and type checking.

Configuration would go into `.pre-commit-config.yaml`. Example as follows:

```yaml
repos:
- repo: https://github.com/google/yapf
  rev: v0.43.0
  hooks:
  - id: yapf
    args: [--in-place, --verbose]
- repo: https://github.com/PyCQA/isort
  rev: 6.0.1
  hooks:
  - id: isort
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.11.7
  hooks:
  - id: ruff
    args: [--output-format, github, --fix]
  - id: ruff-format
- repo: https://github.com/codespell-project/codespell
  rev: v2.4.1
  hooks:
  - id: codespell
    additional_dependencies: ['tomli']
    args: ['--toml', 'pyproject.toml']
- repo: https://github.com/pre-commit/mirrors-clang-format
  rev: v20.1.3
  hooks:
  - id: clang-format
    types_or: [c++, cuda]
    args: [--style=file, --verbose]
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.15.0'
    hooks:
    - id: mypy
      #args: [--strict, --ignore-missing-imports]
      additional_dependencies: [tokenize-rt==6.1.0]  # For better dynamic analysis performance
```

### Conclusion

It was decided to go with **Proposed Change 2: [pre-commit](https://pre-commit.com/)**. The reason being is that it is better at managing code quality tools. In addition, it can automate the running of the tools when users are committing changes. A hybrid with [tox](https://tox.wiki) was considered but because unit tests are not being run in GitHub workflows but with `buildkite`, then the advantages on introducing another tool was negligible.

### CC List.

No response

### Any Other Things.

No response
